Add option for verifying SSL certs w/ postgres JDBC driver
- Add `sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory` to the
connection string for postgres JDBC when using `sslmode=verify-full`
or `sslmode=verify-ca`
- This avoids using the new `org.postgresql.ssl.LibPQFactory` from the
postgres JDBC driver which causes failures which say that the certs are
not at the expected filesystem paths
- Fixes this error message:
```
org.postgresql.util.PSQLException: Could not open SSL root certificate file /Users/pivotal/.postgresql/root.crt.
```

[#163703944]

Signed-off-by: Joshua Casey <jcasey@pivotal.io>
Co-authored-by: Joshua Casey <jcasey@pivotal.io>