Revert "Bump github.com/cloudfoundry/bosh-utils in /src/acceptance_tests"
This reverts commit 8ce6dab476300cab99a1803f3f8ab9c18c439d75.

as this breaks CI:
```
../../pkg/mod/github.com/onsi/gomega@v1.33.0/internal/async_assertion.go:556:19: undefined: context.Cause
note: module requires Go 1.20
```