fix: Bump required minimum go version from 1.13 to 1.20
- As gomega 1.31 requires go 1.20, as shown in the error message as follows:
```
+ pushd /tmp/build/f541ec31/uaa-release/src/acceptance_tests

/tmp/build/f541ec31/uaa-release/src/acceptance_tests /tmp/build/f541ec31

+ ginkgo -v --progress --trace -keepGoing -randomizeAllSpecs -randomizeSuites -race -r .

Failed to compile acceptance_tests:

# github.com/onsi/gomega/internal

../../pkg/mod/github.com/onsi/gomega@v1.31.1/internal/async_assertion.go:556:19: undefined: context.Cause

note: module requires Go 1.20
```